-- public.orders
-- One row per order. Product fields are embedded here (one product per order,
-- matching the current client model). order_items from the original DrawSQL
-- schema is intentionally dropped.

-- Sequence for human-readable order numbers shown to users (ORD-000001 format).
create sequence if not exists public.orders_order_number_seq start 1;

create or replace function public.generate_order_number()
returns trigger
language plpgsql
as $$
begin
  new.order_number := 'ORD-' || lpad(nextval('public.orders_order_number_seq')::text, 6, '0');
  return new;
end;
$$;

create table public.orders (
  id               uuid         not null primary key default gen_random_uuid(),
  order_number     varchar(20)  not null unique,  -- human-readable display ID (ORD-000001)
  user_id          uuid         not null references public.users (id) on delete cascade,
  status           varchar(20)  not null default 'draft'
                   check (status in ('draft','active','out-for-delivery','delivered','paused','completed','cancelled')),
  order_type       varchar(20)  not null
                   check (order_type in ('one-time','recurring')),
  order_nickname   varchar(255) null,     -- auto-generated by app when omitted
  product_name     varchar(255) not null,
  product_type     varchar(50)  not null
                   check (product_type in ('Grocery','Medication','Health & Hygiene','Household','Other')),
  product_quantity int          not null default 1 check (product_quantity > 0),
  store_name       varchar(255) not null,
  store_address    text         not null,
  item_description text         null,     -- optional in form
  ordered_at       timestamptz  null,     -- null for drafts; set when order goes active
  created_at       timestamptz  not null default now(),
  updated_at       timestamptz  not null default now()
);

-- Auto-populate order_number on insert
create trigger set_orders_order_number
  before insert on public.orders
  for each row execute function public.generate_order_number();

-- Keep updated_at current on every write
create trigger set_orders_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();

-- Indexes
create index orders_user_id_idx    on public.orders (user_id);    -- per-user list queries
create index orders_status_idx     on public.orders (status);     -- Orders page status filter
create index orders_ordered_at_idx on public.orders (ordered_at); -- Track page date sorting

-- RLS: enabled, default-deny. Users can only touch their own orders.
alter table public.orders enable row level security;

create policy "orders: select own"
  on public.orders for select
  to authenticated
  using (user_id = auth.uid());

create policy "orders: insert own"
  on public.orders for insert
  to authenticated
  with check (user_id = auth.uid());

create policy "orders: update own"
  on public.orders for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "orders: delete own"
  on public.orders for delete
  to authenticated
  using (user_id = auth.uid());
